postGres/Models/ErrorViewModel.cs
using System;

namespace postGres.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

postGres/Models/PContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace postGres.Models
{
    public class PContext : DbContext
    {
        public PContext (DbContextOptions<PContext> options) : base(options) { }
        public DbSet<Students> students { get; set; }
        public DbSet<Teachers> teachers { get; set; }
    }
    
}

postGres/Models/first.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace postGres.Models
{
    //public class first
    //{
    //    //[ScaffoldColumn(false)]
    //    //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    //    public int id { get; set; }
    //    public string name { get; set; }
    //    public bool isNull { get; set; }
    //}
    public class Students
    {
        //Table[("")]
        //[ScaffoldColumn(false)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        public string name { get; set; }
        public string department { get; set; }
    }
    public class Teachers
    {
        //[ScaffoldColumn(false)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        public string name { get; set; }
        public string department { get; set; }
        public string section { get; set; }
    }
}

postGres/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using postGres.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace postGres.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

postGres/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using postGres.Services.Process_Manager;
using postGres.View_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace postGres.Controllers
{
    public class StudentsController : Controller
    {
        private readonly StudentPM _studentProcessManager;

        public StudentsController(StudentPM studentProcessManager)
        {
            _studentProcessManager = studentProcessManager;

        }
        public async Task<IActionResult> Index()
        {
          var students=await _studentProcessManager.getStudent();
            return View(students);
        }

        [HttpPost]
        public async Task<IActionResult> addStudent(StudentsModel model)
        {
            await _studentProcessManager.insertStudent(model);
            return Redirect("/Students/Index");
        }

        [HttpPost]
        public async Task<IActionResult> AlterStudent(StudentsModel model,string Delete)
        {
            if(string.IsNullOrEmpty(Delete))
            return View(model);
            await _studentProcessManager.deleteStudent(model);
            return Redirect("/Students/Index");

        }
        [HttpPost]
        public async Task<IActionResult> UpdateStudent(StudentsModel model)
        {
            await _studentProcessManager.updateStudent(model);
            return Redirect("/Students/Index");
        }
    }
}

postGres/Controllers/TeachersController.cs
using Microsoft.AspNetCore.Mvc;
using postGres.Services.Process_Manager;
using postGres.View_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace postGres.Controllers
{
    public class TeachersController : Controller
    {
        private readonly TeacherPM _teacherProcessManager;

        public TeachersController(TeacherPM teacherProcessManager)
        {
            _teacherProcessManager = teacherProcessManager;

        }
        public async Task<IActionResult> Index()
        {
            List<TeachersModel> teachers = await _teacherProcessManager.getTeacher();
            return View(teachers);
        }

        [HttpPost]
        public async Task<IActionResult> addTeacher(TeachersModel model)
        {
            await _teacherProcessManager.insertTeacher(model);
            return Redirect("/Teachers/Index");
        }

        [HttpPost]
        public async Task<IActionResult> AlterTeacher(TeachersModel model, string Delete)
        {
            if (string.IsNullOrEmpty(Delete))
                return View(model);
            await _teacherProcessManager.deleteTeacher(model);
            return Redirect("/Teachers/Index");

        }
        [HttpPost]
        public async Task<IActionResult> UpdateTeacher(TeachersModel model)
        {
            await _teacherProcessManager.updateTeacher(model);
            return Redirect("/Teachers/Index");
        }
    }
}

postGres/Views/Home/Index.cshtml
@using postGres.Models
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

postGres/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - postGres</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">School XYZ</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Index">Teachers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - postGres - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

postGres/Views/Students/AlterStudent.cshtml
@using postGres.View_Models
@model StudentsModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditStudent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <table class=" table">
        <tbody>
            <tr>
                <td>
                    <form asp-action="UpdateStudent" asp-controller="Students" method="post" enctype="multipart/form-data">
                        <input type="hidden" asp-for="@Model.id" value="@Model.id" />
                        <input class="form-control-sm d-inline-block" asp-for="@Model.name" value="@Model.name" />
                        <input class="form-control-sm d-inline-block" asp-for="@Model.department" value="@Model.department" />
                        <input type="submit" class="btn-sm btn-primary" value="Update" />
                        <input type="button" onclick="history.back()" class="btn-sm btn-info" value="Cancel" />
                    </form>
                </td>
            </tr>
        </tbody>
    </table>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

postGres/Views/Students/Index.cshtml
@using postGres.View_Models
@model List<StudentsModel>
@{
    Layout = "_Layout";
    ViewData["Title"] = "Students";
}


    
    <form class="my-2" method="post" enctype="multipart/form-data" asp-controller="Students" asp-action="addStudent">
        Name:<input class="form-control-sm d-inline-block" asp-for="@Model.FirstOrDefault().name" value="" />
        Department:<input class="form-control-sm d-inline-block" asp-for="@Model.FirstOrDefault().department" value="" />
        <input class=" btn-sm btn-primary d-inline-block" type="submit" value="Add Student" />
        <hr />
    </form>

    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Department</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (StudentsModel student in Model)
            {
                <tr>
                    <td>@student.name</td>
                    <td>@student.department</td>
                    <td>
                        <form asp-action="AlterStudent" asp-controller="Students" method="post" enctype="multipart/form-data">
                            <input type="hidden" asp-for="@Model.FirstOrDefault().id" value="@student.id"/>
                            <input type="hidden" asp-for="@Model.FirstOrDefault().name" value="@student.name"/>
                            <input type="hidden" asp-for="@Model.FirstOrDefault().department" value="@student.department"/>
                            <input type="submit" name="Edit" class="btn-sm btn-primary" value="Edit" />
                            <input type="submit" name="Delete" class="btn-sm btn-danger" value="Delete" />
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

postGres/Views/Teachers/AlterTeacher.cshtml
@using postGres.View_Models
@model TeachersModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Alter Teachers";
}


    <table class=" table">
        <tbody>
            <tr>
                <td>
                    <form asp-action="UpdateTeacher" asp-controller="Teachers" method="post" enctype="multipart/form-data">
                        <input type="hidden" asp-for="@Model.id" value="@Model.id" />
                        <input class="form-control-sm d-inline-block" asp-for="@Model.name" value="@Model.name" />
                        <input class="form-control-sm d-inline-block" asp-for="@Model.department" value="@Model.department" />
                        <input class="form-control-sm d-inline-block" asp-for="@Model.section" value="@Model.section" />
                        <input type="submit" class="btn-sm btn-primary" value="Update" />
                        <input type="button" onclick="history.back()" class="btn-sm btn-info" value="Cancel" />
                    </form>
                </td>
            </tr>
        </tbody>
    </table>

postGres/Views/Teachers/Index.cshtml
@using postGres.View_Models
@model List<TeachersModel>
@{
    Layout = "_Layout";
    ViewData["Title"] = "Teachers";
}


    
    <form class="my-2" method="post" enctype="multipart/form-data" asp-controller="Teachers" asp-action="addTeacher">
        Name:<input class="form-control-sm d-inline-block" asp-for="@Model.FirstOrDefault().name" value="" />
        Department:<input class="form-control-sm d-inline-block" asp-for="@Model.FirstOrDefault().department" value="" />
        Section:<input class="form-control-sm d-inline-block" asp-for="@Model.FirstOrDefault().section" value="" />
        <input class=" btn-sm btn-primary d-inline-block" type="submit" value="Add Teacher" />
        <hr />
    </form>

    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Department</th>
                <th>Section</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (TeachersModel teacher in Model)
            {
                <tr>
                    <td>@teacher.name</td>
                    <td>@teacher.department</td>
                    <td>@teacher.section</td>
                    <td>
                        <form asp-action="AlterTeacher" asp-controller="Teachers" method="post" enctype="multipart/form-data">
                            <input type="hidden" asp-for="@Model.FirstOrDefault().id" value="@teacher.id" />
                            <input type="hidden" asp-for="@Model.FirstOrDefault().name" value="@teacher.name"/>
                            <input type="hidden" asp-for="@Model.FirstOrDefault().department" value="@teacher.department"/>
                            <input type="hidden" asp-for="@Model.FirstOrDefault().section" value="@teacher.section"/>
                            <input type="submit" name="Edit" class="btn-sm btn-primary" value="Edit" />
                            <input type="submit" name="Delete" class="btn-sm btn-danger" value="Delete" />
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>